### ISSUE TITLE
Thank you ❤️

### ISSUE THREAD

**Issue by lirantal** [the-value-crew/ramroCode#3]
Hey folks,

I wanted to drop by and say thanks for building this ❤️
This helps creating beautiful text snippets and it saved me this weekend when I needed to build a whole new deck quickly for a conference.

Keep up the great work. This is amazing ✨

**Comment by bibhuticoder** [comment]
Wow! Thanks 

We are glad to hear that our RamroCode helped you.  Hope your conference goes well 😊
